service: noteable-aws-sls
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: tobbesoren_test
  region: eu-north-1
  iam:
    role: arn:aws:iam::564920371550:role/tobbesoren-ma22

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  signUp:
    handler: lambdaFunctions/signUp/index.handler
    events:
      - httpApi:
          path: '/api/user/signUp'
          method: POST

  login:
    handler: lambdaFunctions/login/index.handler
    events:
      - httpApi:
          path: '/api/user/login'
          method: POST

  postNote:
    handler: lambdaFunctions/postNote/index.handler
    events:
      - httpApi:
          path: '/api/notes'
          method: POST

  getNotes:
    handler: lambdaFunctions/getNotes/index.handler
    events:
      - httpApi:
          path: '/api/notes'
          method: GET

  getArchivedNotes:
    handler: lambdaFunctions/getArchivedNotes/index.handler
    events:
      - httpApi:
          path: '/api/notes/archived'
          method: GET

  archiveNote:
    handler: lambdaFunctions/archiveNote/index.handler
    events:
      - httpApi:
          path: '/api/notes/archive'
          method: PATCH

  unArchiveNote:
    handler: lambdaFunctions/unArchiveNote/index.handler
    events:
      - httpApi:
          path: '/api/notes/unArchive'
          method: PATCH
  
  updateNote:
    handler: lambdaFunctions/updateNote/index.handler
    events:
      - httpApi:
          path: '/api/notes/{noteId}'
          method: PUT

  deleteArchivedNote:
    handler: lambdaFunctions/deleteArchivedNote/index.handler
    events:
      - httpApi:
          path: '/api/notes/archived'
          method: DELETE  

resources:
  Resources:
    noteableNotesDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: noteableNotes
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: noteId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: noteId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    noteableUsersDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: noteableAccounts
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST